### ISSUE TITLE
KeyError when running the code

### ISSUE THREAD

**Issue by sagnikbm** [shun1024/weighted-deepwalk#5]
Hi, I am trying to use the weighted graph. It would be very helpful if you could give an example that runs.

Weighted edge list:

0 2 7
1 2 7
3 2 7
4 3 7
4 5 7

Command: deepwalk --input  test.edgelist --format weighted_edgelist --output test.embeddings

Error:
Number of nodes: 6
Number of walks: 60
Data size (walks*length): 2400
Walking...
Traceback (most recent call last):
  File "c:\users\sagni\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sagni\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sagni\Anaconda3\Scripts\deepwalk.exe\__main__.py", line 9, in <module>
  File "c:\users\sagni\anaconda3\lib\site-packages\deepwalk\__main__.py", line 144, in main
    process(args)
  File "c:\users\sagni\anaconda3\lib\site-packages\deepwalk\__main__.py", line 73, in process
    walks = weighted_random_walk.random_walk(G, num_paths=args.number_walks, path_length=args.walk_length, alpha=0)
  File "c:\users\sagni\anaconda3\lib\site-packages\deepwalk\weighted_random_walk.py", line 51, in random_walk
    transitionMatrix = getTransitionMatrix(G, nodes)
  File "c:\users\sagni\anaconda3\lib\site-packages\deepwalk\weighted_random_walk.py", line 14, in getTransitionMatrix
    _**neighs = network.neighbors(nodes[i])**_
  File "c:\users\sagni\anaconda3\lib\site-packages\networkx\classes\reportviews.py", line 178, in __getitem__
    **return self._nodes[n]
KeyError: 0**

**Comment by zhiyuanjiang** [comment]
hello sagnikbm, I also encounted this problem. nodes[i] is dict type, you should change nodes type:
nodes = list(nodes)

**Comment by sagnikbm** [comment]
Thank you, I think that solves one problem. I added these lines:

def getTransitionMatrix(network, nodes):
	**nodes = list(nodes)**
	
When it runs, it throws this error.

Number of nodes: 6
Number of walks: 60
Data size (walks*length): 2400
Walking...
<dict_keyiterator object at 0x000001FEE039FC78>
<dict_keyiterator object at 0x000001FEE039FCC8>
<dict_keyiterator object at 0x000001FEE039FC78>
<dict_keyiterator object at 0x000001FEE039FCC8>
<dict_keyiterator object at 0x000001FEE039FC78>
<dict_keyiterator object at 0x000001FEE039FCC8>
Traceback (most recent call last):
  File "c:\users\sagni\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sagni\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sagni\Anaconda3\Scripts\deepwalk.exe\__main__.py", line 9, in <module>
  File "c:\users\sagni\anaconda3\lib\site-packages\deepwalk\__main__.py", line 144, in main
    process(args)
  File "c:\users\sagni\anaconda3\lib\site-packages\deepwalk\__main__.py", line 73, in process
    walks = weighted_random_walk.random_walk(G, num_paths=args.number_walks, path_length=args.walk_length, alpha=0)
  File "c:\users\sagni\anaconda3\lib\site-packages\deepwalk\weighted_random_walk.py", line 60, in random_walk
    indexList = generateSequence(i, transitionMatrix, path_length, alpha)
  File "c:\users\sagni\anaconda3\lib\site-packages\deepwalk\weighted_random_walk.py", line 44, in generateSequence
    nextIndex = np.random.choice(len(probs), 1, p=probs)[0]
  File "mtrand.pyx", line 1148, in mtrand.RandomState.choice
**ValueError: probabilities do not sum to 1**

Any suggestions on this?

**Comment by zhiyuanjiang** [comment]
in function getTransitionMatrix, you also should change neighors type:
neighs = list(network.neighbors(nodes[i])).
in function random_walk, you should do this:
sentence = [nodes[tmp] for tmp in indexList]
nodes[tmp] not neet change to int.
last, in __main__py, add model.wv.save_word2vec_format(args.output)

**Comment by zhiyuanjiang** [comment]
hello sagnikbm, this is the code:
`import networkx as nx
import numpy as np
import random

def getTransitionMatrix(network, nodes):

	matrix = np.empty([len(nodes), len(nodes)])

	
	for i in range(0, len(nodes)):
		
		neighs = list(network.neighbors(nodes[i]))
		
		sums = 0
		for neigh in neighs:
			sums += network[nodes[i]][neigh]['weight']

		for j in range(0, len(nodes)):
			if i == j :
				matrix[i,j] = 0
			else:
				if nodes[j] not in neighs:
					matrix[i, j] = 0
				else:
					matrix[i, j] = network[nodes[i]][nodes[j]]['weight'] / sums
					#print("bbb")
	return matrix

def generateSequence(startIndex, transitionMatrix, path_length, alpha):
	result = [startIndex]
	current = startIndex

	for i in range(0, path_length):
		if random.random() < alpha:
			nextIndex = startIndex
		else:
			probs = transitionMatrix[current]
			#print(probs)
			nextIndex = np.random.choice(len(probs), 1, p=probs)[0]

		result.append(nextIndex)
		current = nextIndex

	return result

def random_walk(G, num_paths, path_length, alpha):
	nodes = list(G.nodes())
	print(type(nodes))
	transitionMatrix = getTransitionMatrix(G, nodes)
	#print(transitionMatrix)
	sentenceList = []

	for i in range(0, len(nodes)):
		for j in range(0, num_paths):
			indexList = generateSequence(i, transitionMatrix, path_length, alpha)
			sentence = [nodes[tmp] for tmp in indexList]
			sentenceList.append(sentence)

	return sentenceList`

**Comment by zhiyuanjiang** [comment]
code: 
```python
**import networkx as nx
import numpy as np
import random

def getTransitionMatrix(network, nodes):

	matrix = np.empty([len(nodes), len(nodes)])

	
	for i in range(0, len(nodes)):
		
		neighs = list(network.neighbors(nodes[i]))
		
		sums = 0
		for neigh in neighs:
			sums += network[nodes[i]][neigh]['weight']

		for j in range(0, len(nodes)):
			if i == j :
				matrix[i,j] = 0
			else:
				if nodes[j] not in neighs:
					matrix[i, j] = 0
				else:
					matrix[i, j] = network[nodes[i]][nodes[j]]['weight'] / sums
					#print("bbb")
	return matrix

def generateSequence(startIndex, transitionMatrix, path_length, alpha):
	result = [startIndex]
	current = startIndex

	for i in range(0, path_length):
		if random.random() < alpha:
			nextIndex = startIndex
		else:
			probs = transitionMatrix[current]
			#print(probs)
			nextIndex = np.random.choice(len(probs), 1, p=probs)[0]

		result.append(nextIndex)
		current = nextIndex

	return result

def random_walk(G, num_paths, path_length, alpha):
	nodes = list(G.nodes())
	print(type(nodes))
	transitionMatrix = getTransitionMatrix(G, nodes)
	#print(transitionMatrix)
	sentenceList = []

	for i in range(0, len(nodes)):
		for j in range(0, num_paths):
			indexList = generateSequence(i, transitionMatrix, path_length, alpha)
			sentence = [nodes[tmp] for tmp in indexList]
			sentenceList.append(sentence)

	return sentenceList**
```

**Comment by sagnikbm** [comment]
Thank you zhiyuanjiang  for your help. The code works now.

I was wondering if you could give an example so that I would understand how it actually works.
I have used the following example with 2 embedding as output: 

0 1 9
0 2 9
2 1 9
2 3 1
3 4 9
3 5 9
4 5 9

>>deepwalk --input test.edgelist --format weighted_edgelist --output test.embeddings

My output was:

6 2
2 1.6615189 0.27572834
3 1.4440609 0.26924816
1 1.3572017 0.1387987
0 1.3930184 0.18084836
4 1.5306126 0.3947549
5 1.1271592 0.46383873

I am not able to interpret the weighted edges with the output.

**Comment by zhiyuanjiang** [comment]
Hello sagnikbm. First, you should understand deepwalk, and weighted-deepwalk just add a process of random-walking. In the procee of random-walking, author is using the function **np.random.choice** to select next node.
**getTransitionMatrix** build a probability matrix.
**generateSequence** build a random-walking sequence for node.

**Comment by sagnikbm** [comment]
Hi zhiyuanjiang, I did read the paper on deepwalk. However, there was no concept of edge weights in the paper. I am just wondering how are the edge weights taken into consideration in this weighted deepwalk? What is the purpose of the edge weights? (my understanding is that edge weights somehow define probability of transition during the random walk).

**Comment by zhiyuanjiang** [comment]
Hi sagnikbm, I think your understanding is correct.  Edge weights define probability of transiton during the random walk.  My statement above have some problem.
the author calculate the probability from node i to node j.
**sums += network[nodes[i]][neigh]['weight']**
**matrix[i, j] = network[nodes[i]][nodes[j]]['weight'] / sums**

**Comment by sagnikbm** [comment]
Thank you zhiyuanjiang for all your help, I think this thread will be helpful for people in future!

**Comment by omidjahadi** [comment]
`Traceback (most recent call last):

          File "/usr/local/bin/deepwalk", line 8, in <module>

            sys.exit(main())

          File "/usr/local/lib/python3.7/dist-packages/deepwalk/__main__.py", line 145, in main

            process(args)

          File "/usr/local/lib/python3.7/dist-packages/deepwalk/__main__.py", line 73, in process

            walks = weighted_random_walk.random_walk(G, num_paths=args.number_walks,path_length=args.walk_length, 

alpha=0)

          File "/usr/local/lib/python3.7/dist-packages/deepwalk/weighted_random_walk.py", line 45, in random_walk

            sentence = [nodes[tmp] for tmp in indexList]

          File "/usr/local/lib/python3.7/dist-packages/deepwalk/weighted_random_walk.py", line 45, in <listcomp>

            sentence = [nodes[tmp] for tmp in indexList]

          File "/usr/local/lib/python3.7/dist-packages/networkx/classes/reportviews.py", line 193, in __getitem__

            return self._nodes[n]

        KeyError: 0`

I still have this error.
